name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            artifact_name: utorr-linux-amd64
          - goos: windows
            goarch: amd64
            artifact_name: utorr-windows-amd64.exe
          - goos: darwin
            goarch: amd64
            artifact_name: utorr-darwin-amd64
          - goos: darwin
            goarch: arm64
            artifact_name: utorr-darwin-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Build
        run: |
          mkdir -p builds
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -v -o "builds/${{ matrix.artifact_name }}" .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: builds/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
